config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :entries
  root 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.order(created_at: :desc).all
    @entry = Entry.new
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    if current_user
      @entry.user_id = current_user.id
    else
      @entry.user_id = 0
    end
    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_path , notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	@users = User.all
end

def show
	@user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/application/_usernav.html.erb
<% if current_user %>
	Welcome <%= link_to current_user.username , current_user %>
<% else %>
	<%= link_to "Login" , new_user_session_path %>
<% end %>

app/views/entries/_form.html.erb
<%= bootstrap_form_for @entry , html:{class:"minimalistic"} do |f| %>
<div id="form_box">

	<div id="head">
	<span>Write your observation or hypothesis here...</span>
	<%= f.submit :Post , class:"btn pull-right" %>
	</div>

	<div id="body">
    <%= f.text_area :body , hide_label: true , placeholder: "Here ya go..." %>
	</div>

</div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div id="entryform">
  <%= render "form" %>
</div>

<div id="entries">
  <table class="table table-striped">
    <tbody>
      <% @entries.each do |entry| %>
        <tr>
          <td><%= Texty.new(entry.body).tags_autolink.html_safe %></td>
          <td><%= link_to entry.user.username , entry.user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @entry.user_id %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%# NOT ADAPTED FOR MD,SM,XS SCREENS YET %>
<html>
<head>
  <title>Sayaahi</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header" class="row col-xs-12">
	<div id="logo" class="pull-left"><%= image_tag "logo.png" %></div>
	<div id="usernav" class="pull-right">
		<%= render 'usernav' %>
	</div>
</div>

<div id="content" class="col-xs-12">
	<%= yield %>
</div>

</body>
</html>

app/views/users/show.html.erb
<h1>Placeholder page for user profiles</h1>

<b>Username:</b> <%= @user.username %>